---
- name: Check if previous instance of client exists
  community.windows.win_domain_computer:
    name: '{{ domain_computer_name }}'
    state: absent
  delegate_to: '{{ domain_pdc }}'
  vars:
    ansible_user: '{{ domain_admin_user }}'
    ansible_become_user: '{{ domain_admin_user }}'
    ansible_password: '{{ domain_admin_password }}'
  check_mode: true
  register: prev

- name: Remove previous instance of DC if not domain joined yet
  community.windows.win_domain_computer:
    name: '{{ domain_computer_name }}'
    state: absent
  when: prev.changed and not ansible_facts['windows_domain_member']
  delegate_to: '{{ domain_pdc }}'
  vars:
    ansible_user: '{{ domain_admin_user }}'
    ansible_become_user: '{{ domain_admin_user }}'
    ansible_password: '{{ domain_admin_password }}'

- name: Join client to domain
  ansible.windows.win_domain_membership:
    dns_domain_name: '{{ domain_name }}'
    domain_admin_user: '{{ domain_admin_user }}'
    domain_admin_password: '{{ domain_admin_password }}'
    # domain_ou_path: '{{ domain_ou_path }}'
    hostname: '{{ domain_computer_name }}'
    state: domain
  register: domain_join

- name: Reboot
  ansible.windows.win_reboot:
  when: domain_join.reboot_required
